In [13]:
import pandas as pd
import nltk 
from nltk.tokenize import word_tokenize
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelEncoder,OrdinalEncoder
from nltk.corpus import stopwords

In [14]:
df = pd.read_csv(r'ml_resume_dataset_4500.csv')

In [15]:
df.sample(5)

,id,name,years_experience,highest_degree,skills,current_title,has_portfolio,raw_text,label
2740,2741,Mehdi Hasan,0.0,Masters,"SQLAlchemy, Scikit-learn, Kubernetes, Reinforc...",Office Assistant,False,Recent graduate with coursework in statistics ...,0
2506,2507,Kamal Bhuiyan,12.0,Masters,"Azure, Clustering, Data Visualization, EDA, GC...",NLP Engineer,True,Data scientist proficient in end-to-end ML pip...,1
1610,1611,Farah Biswas,5.0,Bachelors,"PyTorch, Flask",Marketing Intern,False,Sales professional with strong communication s...,0
2321,2322,Arafat Siddique,2.0,Bachelors,"Docker Compose, Streamlit, Transformer Models,...",Sales Executive,False,Receptionist experienced in communication and ...,0
520,521,Firoz Rahman,0.0,Bachelors,"Hadoop, GPT",Administrative Assistant,False,Junior intern with exposure to data labeling a...,0

In [16]:
df= df.drop(columns = ['id'])

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4500 entries, 0 to 4499
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   name              4500 non-null   str
 1   years_experience  4500 non-null   float64
 2   highest_degree    4500 non-null   str
 3   skills            4500 non-null   str
 4   current_title     4500 non-null   str
 5   has_portfolio     4500 non-null   bool
 6   raw_text          4500 non-null   str
 7   label             4500 non-null   int64
dtypes: bool(1), float64(1), int64(1), str(5)
memory usage: 1.0 MB

In [18]:
import numpy as np
label = LabelEncoder()
Ord = OrdinalEncoder()
a= np.array(df['highest_degree'])
a = a.reshape(-1,1)
df['has_portfolio_encoded'] = label.fit_transform(df['has_portfolio'])
df['highest_degree_encoded'] = Ord.fit_transform(a)
df = df.drop(columns = ['has_portfolio','highest_degree'])

In [19]:
df.sample()

,name,years_experience,skills,current_title,raw_text,label,has_portfolio_encoded,highest_degree_encoded
1294,Hasan Islam,4.0,"Python, Matplotlib, Computer Vision, Transform...",Administrative Assistant,Receptionist experienced in communication and ...,0,0,0.0

## Making Functions for NLP

In [1]:
def rem_stopwords(text):
    if text.isna():
        return ''
    words  = stopwords.words('english')
    return "".join(
        words for words in text.split()
        if words.lower() not in words
         
    )

0