In [21]:
import pandas as pd
import nltk 
from nltk.tokenize import word_tokenize
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelEncoder,OrdinalEncoder
from nltk.corpus import stopwords

In [22]:
df = pd.read_csv(r'ml_resume_dataset_4500.csv')

In [23]:
df.sample(5)

,id,name,years_experience,highest_degree,skills,current_title,has_portfolio,raw_text,label
449,450,Sakib Siddique,1.0,Bachelors,"Hadoop, Transformer Models, Data Visualization...",Customer Support,False,Junior intern with exposure to data labeling a...,0
413,414,Salma Ahmed,0.0,Bachelors,"PyTorch Lightning, GPT, FastAPI, Pandas, SQLAl...",Data Entry Operator,False,Sales professional with strong communication s...,0
961,962,Monir Siddique,4.0,Bachelors,"Classification, Computer Vision, Data Visualiz...",Research Scientist,True,"NLP specialist skilled in text preprocessing, ...",1
1696,1697,Nabila Khan,3.0,PhD,"CI/CD, FastAPI, Git, HuggingFace, NumPy, Panda...",Data Scientist,True,"ML engineer experienced in MLOps, Docker, Kube...",1
1471,1472,Hasan Das,3.0,Bachelors,"CI/CD, Matplotlib",Receptionist,True,Marketing intern with experience in social med...,0

In [24]:
df= df.drop(columns = ['id'])

In [25]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4500 entries, 0 to 4499
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   name              4500 non-null   str
 1   years_experience  4500 non-null   float64
 2   highest_degree    4500 non-null   str
 3   skills            4500 non-null   str
 4   current_title     4500 non-null   str
 5   has_portfolio     4500 non-null   bool
 6   raw_text          4500 non-null   str
 7   label             4500 non-null   int64
dtypes: bool(1), float64(1), int64(1), str(5)
memory usage: 1.0 MB

In [ ]:
import numpy as np
label = LabelEncoder()
Ord = OrdinalEncoder()
a= np.array(df['highest_degree'])
a = a.reshape(-1,1)
df['has_portfolio_encoded'] = label.fit_transform(df['has_portfolio'])
df['highest_degree_encoded'] = Ord.fit_transform(a)
df = df.drop(columns = ['has_portfolio','highest_degree'])

a.clear()

In [45]:
df.sample()

,name,years_experience,skills,current_title,raw_text,label,has_portfolio_encoded,highest_degree_encoded
4327,Sadia Shah,2.0,"Linux, Data Visualization",Customer Support,Junior intern with exposure to data labeling a...,0,1,1.0

0