In [ ]:
import pandas as pd
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk import text
from sklearn.preprocessing import OneHotEncoder

In [29]:
df = pd.read_csv(r'resume_dataset_1200.csv')

In [30]:
df.sample(5)

,Name,Age,Gender,Education_Level,Field_of_Study,Degrees,Institute_Name,Graduation_Year,Experience_Years,Current_Job_Title,Previous_Job_Titles,Skills,Certifications,Target_Job_Description
399,Mason Jackson,43,Non-Binary,Master's,Electrical Engineering,Master's in Electrical Engineering,London School of Economics,2016,9,MLOps Specialist,"Software Developer, AI Ethics Officer","Kafka, PyTorch, Cloud Computing, Cybersecurity...",NaN,Looking for an opportunity as a Software Devel...
183,David Wilson,21,Non-Binary,PhD,Information Systems,PhD in Information Systems,University of Washington,2023,2,Software Developer,NaN,"Deep Learning, Agile, DevOps, Jenkins, MongoDB...","Project Management Professional, Oracle Certif...",Targeting a Software Developer position to uti...
81,Arjun Garcia,36,Male,Bachelor's,Electrical Engineering,Bachelor's in Electrical Engineering,Massachusetts Institute of Technology,2017,1,Big Data Engineer,NaN,"Ansible, Azure, SQL, Node.js, Git, REST APIs, ...","Oracle Certified Professional, Certified Ethic...",Targeting a Big Data Engineer position to util...
299,Meera Pillai,28,Male,Bachelor's,Information Systems,Bachelor's in Information Systems,Delhi University,2021,4,Software Developer,NaN,"Kafka, Penetration Testing, Cybersecurity, Dat...","CompTIA Security+, Certified Kubernetes Admini...",Looking for an opportunity as a AI Ethics Offi...
630,Charlotte Srinivasan,42,Non-Binary,PhD,Artificial Intelligence,PhD in Artificial Intelligence,Christian Medical College,2025,0,NaN,NaN,"Scrum, Solidity, Cybersecurity, Jenkins",NaN,Seeking a challenging role as a Full-Stack Dev...

In [31]:
df.isna().sum()

Name                        0
Age                         0
Gender                      0
Education_Level             0
Field_of_Study              0
Degrees                     0
Institute_Name              0
Graduation_Year             0
Experience_Years            0
Current_Job_Title         441
Previous_Job_Titles       914
Skills                      0
Certifications            319
Target_Job_Description      0
dtype: int64

In [ ]:
df = df.drop(columns= ['Name','Current_Job_Title','Previous_Job_Titles','Certifications'])

In [ ]:
ohe = OneHotEncoder()
ohe.fit_transform(df['Gender'])

,Age,Gender,Education_Level,Field_of_Study,Degrees,Institute_Name,Graduation_Year,Experience_Years,Skills,Target_Job_Description
0,30,Non-Binary,Master's,Cybersecurity,Master's in Cybersecurity,University of Pennsylvania,2025,0,"Node.js, JavaScript, Deep Learning, Statistics...",Seeking a challenging role as a Software Devel...
1,27,Non-Binary,Bachelor's,Electronics Engineering,Bachelor's in Electronics Engineering,Pune University,2019,5,"Spark, Kubernetes, Terraform, Natural Language...",Targeting a Cybersecurity Engineer position to...
2,45,Male,Bachelor's,Computer Science,Bachelor's in Computer Science,Amity University,2023,2,"Data Analysis, Node.js, Machine Learning, Linu...",Targeting a Prompt Engineer position to utiliz...
3,28,Male,Master's,Information Technology,Master's in Information Technology,University of Pennsylvania,2023,2,"Docker, Kubernetes, Blockchain, Spark",Targeting a Data Scientist position where I ca...
4,42,Non-Binary,Master's,Electronics Engineering,Master's in Electronics Engineering,University of Toronto,2023,2,"Statistics, Blockchain, Kubernetes, Cybersecurity",Looking for an opportunity as a Prompt Enginee...
...,...,...,...,...,...,...,...,...,...,...
1195,37,Female,Bachelor's,Supply Chain Management,Bachelor's in Supply Chain Management,Birla Institute of Technology,2015,9,"Accounting, Financial Analysis, Patient Care, ...",Looking for an opportunity as a Salesperson to...
1196,29,Non-Binary,Master's,Sociology,Master's in Sociology,Birla Institute of Technology,2021,3,"Data Analysis, Risk Management, Medical Knowle...",Seeking a challenging role as a Brand Manager ...
1197,45,Female,Diploma,Chemistry,Diploma in Chemistry,All India Institute of Medical Sciences,2024,0,"Project Management, Medical Knowledge, PowerPo...",Looking for an opportunity as a Counselor to l...
1198,29,Female,Bachelor's,Biology,Bachelor's in Biology,Vellore Institute of Technology,2021,4,"Emotional Intelligence, PowerPoint, Medical Kn...",Looking for an opportunity as a Digital Market...
1199,26,Non-Binary,Master's,Sociology,Master's in Sociology,Amity University,2025,0,"Presentation Skills, Critical Thinking, Time M...",Looking for a Marketing Manager role where I c...