In [65]:
import nltk
import pandas as pd 
import re ## regular Expression
import string,time
from nltk.corpus import stopwords
from nltk import word_tokenize
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [2]:
df = pd.read_csv('IMDB Dataset.csv')
df.head(3)

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive

In [3]:
print(df['review'])

0        One of the other reviewers has mentioned that ...
1        A wonderful little production. <br /><br />The...
2        I thought this was a wonderful way to spend ti...
3        Basically there's a family where a little boy ...
4        Petter Mattei's "Love in the Time of Money" is...
                               ...
49995    I thought this movie did a down right good job...
49996    Bad plot, bad dialogue, bad acting, idiotic di...
49997    I am a Catholic taught in parochial elementary...
49998    I'm going to have to disagree with the previou...
49999    No one expects the Star Trek movies to be high...
Name: review, Length: 50000, dtype: str

## Lower Casing

In [4]:
df['review']= df['review'].str.lower()

In [5]:
df.head(2)

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. <br /><br />the...  positive

## Removing Unnecessary symbols like HTML tags

In [53]:

def remove_tags(text):
    pattern = re.compile('<.*?>')
    return pattern.sub(r'',text)

def remove_punctuations(text):

    return text.translate(str.maketrans('','',string.punctuation))

stop_words = set(stopwords.words('english'))

def rem_stopwords(text):
   
    if pd.isna(text):
        return ""

    return " ".join(
        word for word in text.split()
        if word.lower() not in stop_words
    )

def tokenize(text):
      return " ".join(word_tokenize(text))

In [29]:
df['review'].apply(remove_tags)

0        one of the other reviewers has mentioned that ...
1        a wonderful little production br br the filmin...
2        i thought this was a wonderful way to spend ti...
3        basically theres a family where a little boy j...
4        petter matteis love in the time of money is a ...
                               ...
49995    i thought this movie did a down right good job...
49996    bad plot bad dialogue bad acting idiotic direc...
49997    i am a catholic taught in parochial elementary...
49998    im going to have to disagree with the previous...
49999    no one expects the star trek movies to be high...
Name: review, Length: 50000, dtype: str

In [30]:
df['review'] =df['review'].apply(remove_punctuations)

In [35]:
df['review'] =df['review'].apply(rem_stopwords)

In [57]:
df['review']= df['review'].apply(tokenize)

In [61]:

tfidf = TfidfVectorizer(max_features=5000)

X = tfidf.fit_transform(df['review']).toarray()

In [76]:
import numpy as np

y =np.array( df['sentiment'])
le = LabelEncoder()
y_encoded = le.fit_transform(y)

In [79]:
X_tr,X_tst,y_tr,y_tst=train_test_split(X,y_encoded,test_size = 0.2,random_state = 42)

## Training Model

In [80]:
lg= LogisticRegression()

In [81]:
lg.fit(X_tr,y_tr)

LogisticRegression()

In [82]:
y_pred = lg.predict(X_tst)

In [83]:
accuracy_score(y_pred,y_tst)

0.8883

In [84]:
confusion_matrix(y_tst,y_pred)

array([[4339,  622],
       [ 495, 4544]])

In [85]:
from sklearn.metrics import classification_report

print(classification_report(y_tst, y_pred))

              precision    recall  f1-score   support

           0       0.90      0.87      0.89      4961
           1       0.88      0.90      0.89      5039

    accuracy                           0.89     10000
   macro avg       0.89      0.89      0.89     10000
weighted avg       0.89      0.89      0.89     10000